export const TOURS_ACTION_TYPES = {
  SET_TOURS_DATA: "SET_TOURS_DATA",
  FETCH_TOURS_START: "FETCH_TOURS_START",
  FETCH_TOURS_SUCCESS: "FETCH_TOURS_SUCCESS",
  FETCH_TOURS_FAILURE: "FETCH_TOURS_FAILURE",
};
